### ISSUE TITLE
Overlay subscriptions are incompatible with sensor_data publishers

### ISSUE THREAD

**Issue by Kettenhoax** [ros-sports/rqt_image_overlay#32]
The generic subscription in an overlay plugin is initialized with QoS reliability: reliable.
This makes it incompatible with sensor_data publishers.

There has been a similar discussion in [rqt_image_view#41](https://github.com/ros-visualization/rqt_image_view/issues/41), which led the maintainers to [set the default QoS to sensor_data](https://github.com/ros-visualization/rqt_image_view/pull/67).
Alternatively, a GUI control to set QoS could be added.
Both would solve the issue, I'm not sure about the best option though.

PS: great rqt plugin, thanks!

**Comment by ijnek** [comment]
@Kettenhoax thanks for reporting the issue! I thought I had fixed that a while back in #3, but i had only changed it for the image topic and not for the overlay topics.

This should be resolved by #34, thanks for your contribution.
