### ISSUE TITLE
Feature: Camera Info feature scaling

### ISSUE THREAD

**Issue by devrite** [ros-sports/rqt_image_overlay#61]
Hi everyone,

we created a branch in our projects that introduces handling of `CameraInfo` which are published along with scaled versions of images and their detections, while still displaying them on the original image

A detector for example may use a different aspect ratio or in general a scaled down version of the input and output features in that space while still using the original frame ID. `CameraInfo` handles most cases already (roi, binning, ....). Such a behaviour can be tested using one of the `image_proc` nodes like `decimate`, which publishes an adapted camera_info for that image (along with the decimated image).

What would be the benefit:
* No extra debug images need to be published
* Easier debugging or visualization

How can it be solved (a first working solution https://github.com/AIT-Assistive-Autonomous-Systems/rqt_image_overlay/tree/use_camera_info_humble ):
* Adapt the painter to scale and shift the origin and painting space.
* No adaption in the plugins itself needed.

Current identified issues:
* Since painting space is scaled, text or other resolution dependent painting may look pixelated.
  * Can be worked around using a debug image currently
  * Could be solved by adapting the API with a scaling param or by adding a `get_pixel_from_dpi` to API for plugins to use (or query it from the painter?).
* Currently, the camera_info (as seen in the commits) is set to the namespace of the data topic (plugin topic).
  * In most scenarios this will be the case
  * A subscriber is always created (may not be desired).
  * The topic may reside somewhere else (not in data topic namespace). Which would likely need a configurable param in the GUI.

From our perspective even without fixes for these issues the benefit already outweighs these, but we would like your comments before we start a PR.

PS: We might not have much time to work on this issue besides an initial PR or just may occasionally leave comments, but we will assist as much as we can.

**Comment by ijnek** [comment]
Hi @devrite, thanks for your feature request! I had a look at the branch you posted.

My initial thoughts are against adding this feature and here's why:
* The main intent of this plugin is to display detected objects on the image it was detected in. It expects the incoming message to contain all information for it to be drawn onto the image. This feature is essentially asking the message to be drawn onto a separate image from the one it was detected on, where additional information is required (CameraInfo).
* This increases complexity of the plugin for a rather special use case.

With your use case, here are some of my alternative recommendations that can be done without changes to RQt Image Overlay:
* Create a new debug ROS msg that contains all information to display the message onto the original image. That would be the msg and the CameraInfo. In the overlay plugin you're implementing, do the painter scaling:

```cpp
void SampleLayer::overlay(
  QPainter & painter,
  const custom_msgs::msg::MsgWithCameraInfo & msg)
{
    painter.save();
    if (msg.camera_info && msg.camera_info.width > 0 && msg.camera_info.height > 0) {
      auto binning_x = msg.camera_info.binning_x == 0 ? 1 : msg.camera_info.binning_x;
      auto binning_y = msg.camera_info.binning_y == 0 ? 1 : msg.camera_info.binning_y;
      auto camera_width = msg.camera_info.width / binning_x;
      auto camera_height = msg.camera_info.height / binning_y;
      auto x_scale = painter.viewport().width() / static_cast<double>(camera_width);
      auto y_scale = painter.viewport().height() / static_cast<double>(camera_height);
      painter.translate(QPoint(msg.camera_info.roi.x_offset * x_scale, msg.camera_info.roi.y_offset * y_scale));
      painter.scale(x_scale, y_scale);
    }

    // Draw msg here

    painter.restore();
}
```
* OR Use coordinates that match the original image in your message.
* OR Don't display the messages on the original image, but display them on the modified image

**Comment by devrite** [comment]
@ijnek ´Thanks four your comments. I still hope though that some version of it may find it to the plugins if not the original. Here are our reasons why iterated. Let me know what you think.

I am not sure if I would say it adds much extra complexity as it hides everything from the underlying plugins and it is not much code. To avoid undesired behaviour (currently I can not really think of any) an GUI-flag could be added (disabled on default) that would enable feature space conversion or use the current fixed behaviour (disabled).

I am not sure if the use case is so special as we ourselves either always rescaled features (for processing or debug display) ourselves, or we did not and further processing was in reduced feature space. Or we added code for debug images, which almost looks the same in all nodes, for the same type of message, which is a little bit redundant and may introduce transformation errors while a tested plugin would avoid that. Besides introducing these nodes or code for debug images may affect live performance (bandwith, memory, cpu). I'm quite sure that most of us have written code to handle just that or started nodes just to display these results on the image resp. rescale images.

In rviz, similar operations are perfomred when features are being reprojected to the camera image from 3D. So 3D based features (which could also be overlayed in rqt) will always need the info (of at least the image being overlayed), creating an extra message for all these messages (`vision_msgs`) to just contain all meta data seems a little bit tedious. If you think about what TF is doing it is the same: Transform what you get to the space you need it in instead of publishing it to every needed space as well as not publishing the whole TF tree along with the actual message. Besides if you would want to overlay 3D detections you might even need TF access in the plugin.

Actually our contribution could even be improved if you do not want them to be displayed on the original but even smaller image (for bandwith reasons). Also something I have seen a lot when people working with remote devices over slow links or not so reliable links. In this case the plugin would even need to consider the info of the overlayed image too (just like for 3D). But this can be a next step.

If this does not meet your requirements, that is totally fine, we just thought we share that need with more people.

There maybe alternatives that I have not looked into yet. Since plugins they are not bound to the message type in the interface and a new layer for the same message can be created a new plugin base/API resp. just another overlay derived from this as a base.

Thanks for your thoughts!

**Comment by devrite** [comment]
Will close it for now. If I have time to work on an alternative or anybody has extra ideas, we can reopen it.
